version: '3.8'

services:
  nepali-tts:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./output:/app/output
      - ./src:/app/src       # For development
      - ./public:/app/public
    environment:
      - NODE_ENV=production
    restart: unless-stopped